/**
 * @module types
 *
 * Shared TypeScript types and interfaces used throughout the Code Agent
 * application. Centralising them here prevents circular imports and makes
 * the data model easy to discover.
 */

/**
 * Metadata record persisted to disk for every successfully ingested document.
 *
 * One JSON file per document is written to `<dataDir>/documents/<id>.json`
 * so that the `store list` command can display the registry without querying
 * Pinecone.
 */
export interface IngestedDocument {
  /** Unique identifier (UUID v4) assigned at ingest time. */
  id: string;
  /** Absolute file path of the original document. */
  source: string;
  /** File format detected from the extension, e.g. `"txt"`, `"md"`, `"pdf"`. */
  format: string;
  /** Number of text chunks that were embedded and upserted into Pinecone. */
  chunkCount: number;
  /** ISO 8601 timestamp recorded when the document was ingested. */
  ingestedAt: string;
}

/**
 * A single chunk returned by a Pinecone similarity search, together with its
 * relevance score and the source document it came from.
 */
export interface RetrievalResult {
  /** Raw text content of the retrieved chunk. */
  content: string;
  /** Absolute path of the source document this chunk belongs to. */
  source: string;
  /** Cosine similarity score in the range 0–1 (higher is more relevant). */
  score: number;
}

/**
 * A single message in the chat conversation, as stored in React state and
 * written to the terminal via Ink.
 */
export interface ChatMessage {
  /** Unique identifier (UUID v4) for this message. */
  id: string;
  /**
   * Originator of the message.
   * - `"user"` — typed by the human.
   * - `"assistant"` — generated by the LLM.
   * - `"system"` — in-app notice (e.g. `/help` output, ingest confirmation).
   */
  role: "user" | "assistant" | "system" | "developer" | "tester"; // system = in-app notices
  /** Text body of the message. */
  content: string;
  /**
   * Retrieval results that grounded this response.
   * Only present on `"assistant"` messages produced in chat mode.
   */
  sources?: RetrievalResult[];
  /** ISO 8601 timestamp recorded when the message was created. */
  timestamp: string;
}

/**
 * Supported LLM provider identifiers.
 *
 * - `"anthropic"` — uses the Claude family of models via `@langchain/anthropic`.
 * - `"openai"` — uses GPT models via `@langchain/openai`.
 * - `"google"` — uses Google models via `@langchain/google`.
 */
export type Provider = "anthropic" | "openai" | "google";

/**
 * Canonical configuration shape for the entire application.
 *
 * Values are resolved in layers (lowest → highest priority):
 * built-in defaults → `code-agent.config.json` → environment variables →
 * CLI flags. See {@link loadConfig} for the merge logic.
 */
export interface AppConfig {
  /**
   * Settings for the planner agent used in team mode.
   *
   * The planner interprets user requirements and coordinates the developer
   * and tester sub-agents.
   */
  planner: {
    /** LLM provider for the planner agent. */
    provider: Provider;
    /** Model identifier for the planner (typically a more capable model). */
    model: string;
    /** Sampling temperature for the planner. */
    temperature: number;
    /** Maximum tokens the planner may generate per turn. */
    maxTokens: number;
  };
  /**
   * Settings for the developer sub-agent used in team mode.
   *
   * The developer receives implementation specifications from the planner and
   * uses filesystem tools to read and write code.
   */
  developer: {
    /** LLM provider for the developer agent. */
    provider: Provider;
    /** Model identifier for the developer. */
    model: string;
    /** Sampling temperature for the developer (lower = more deterministic). */
    temperature: number;
    /** Maximum tokens the developer may generate per turn. */
    maxTokens: number;
  };
  /**
   * Settings for the tester sub-agent used in team mode.
   *
   * The tester verifies developer output by writing and running tests.
   */
  tester: {
    /** LLM provider for the tester agent. */
    provider: Provider;
    /** Model identifier for the tester. */
    model: string;
    /** Sampling temperature for the tester (lower = more deterministic). */
    temperature: number;
    /** Maximum tokens the tester may generate per turn. */
    maxTokens: number;
  };
  /**
   * List of shell command patterns that are pre-approved and do not require
   * interactive user confirmation before execution. Each string is converted
   * to a `RegExp` and tested against the full command string. If any pattern
   * matches, the command runs without prompting.
   *
   * Example: `["^bun test", "^bun exec tsc"]`
   */
  allowedCommands: string[];
}
