/**
 * @module types
 *
 * Shared TypeScript types and interfaces used throughout the RAG Starter
 * application. Centralising them here prevents circular imports and makes
 * the data model easy to discover.
 */

/**
 * Metadata record persisted to disk for every successfully ingested document.
 *
 * One JSON file per document is written to `<dataDir>/documents/<id>.json`
 * so that the `store list` command can display the registry without querying
 * Pinecone.
 */
export interface IngestedDocument {
  /** Unique identifier (UUID v4) assigned at ingest time. */
  id: string;
  /** Absolute file path of the original document. */
  source: string;        // absolute file path
  /** File format detected from the extension, e.g. `"txt"`, `"md"`, `"pdf"`. */
  format: string;        // txt, md, pdf
  /** Number of text chunks that were embedded and upserted into Pinecone. */
  chunkCount: number;
  /** ISO 8601 timestamp recorded when the document was ingested. */
  ingestedAt: string;    // ISO timestamp
}

/**
 * A single chunk returned by a Pinecone similarity search, together with its
 * relevance score and the source document it came from.
 */
export interface RetrievalResult {
  /** Raw text content of the retrieved chunk. */
  content: string;
  /** Absolute path of the source document this chunk belongs to. */
  source: string;
  /** Cosine similarity score in the range 0–1 (higher is more relevant). */
  score: number;         // cosine similarity 0–1
}

/**
 * A single message in the chat conversation, as stored in React state and
 * written to the terminal via Ink.
 */
// A single message in the chat UI
export interface ChatMessage {
  /** Unique identifier (UUID v4) for this message. */
  id: string;
  /**
   * Originator of the message.
   * - `"user"` — typed by the human.
   * - `"assistant"` — generated by the LLM.
   * - `"system"` — in-app notice (e.g. `/help` output, ingest confirmation).
   */
  role: "user" | "assistant" | "system";  // system = in-app notices
  /** Text body of the message. */
  content: string;
  /**
   * Retrieval results that grounded this response.
   * Only present on `"assistant"` messages produced in chat mode.
   */
  sources?: RetrievalResult[];            // only on assistant messages
  /** ISO 8601 timestamp recorded when the message was created. */
  timestamp: string;
}

/**
 * Supported LLM provider identifiers.
 *
 * - `"anthropic"` — uses the Claude family of models via `@langchain/anthropic`.
 * - `"openai"` — uses GPT models via `@langchain/openai`.
 */
export type Provider = "anthropic" | "openai";

/**
 * Canonical configuration shape for the entire application.
 *
 * Values are resolved in layers (lowest → highest priority):
 * built-in defaults → `rag-starter.config.json` → environment variables →
 * CLI flags. See {@link loadConfig} for the merge logic.
 */
export interface AppConfig {
  /**
   * Settings for the primary chat / RAG LLM.
   */
  llm: {
    /** LLM provider to use for chat responses. */
    provider: Provider;
    /** Model identifier string (e.g. `"claude-sonnet-4-6"`). */
    model: string;
    /** Sampling temperature — higher values produce more varied output. */
    temperature: number;
    /** Maximum number of tokens the model may generate per response. */
    maxTokens: number;
  };
  /**
   * Settings for the planner agent used in team mode.
   *
   * The planner interprets user requirements and coordinates the developer
   * and tester sub-agents.
   */
  planner: {
    /** LLM provider for the planner agent. */
    provider: Provider;
    /** Model identifier for the planner (typically a more capable model). */
    model: string;
    /** Sampling temperature for the planner. */
    temperature: number;
    /** Maximum tokens the planner may generate per turn. */
    maxTokens: number; 
  },
  /**
   * Settings for the developer sub-agent used in team mode.
   *
   * The developer receives implementation specifications from the planner and
   * uses filesystem tools to read and write code.
   */
  developer: {
    /** LLM provider for the developer agent. */
    provider: Provider;
    /** Model identifier for the developer. */
    model: string;
    /** Sampling temperature for the developer (lower = more deterministic). */
    temperature: number;
    /** Maximum tokens the developer may generate per turn. */
    maxTokens: number;
  },
  /**
   * Settings for the tester sub-agent used in team mode.
   *
   * The tester verifies developer output by writing and running tests.
   */
  tester: {
    /** LLM provider for the tester agent. */
    provider: Provider;
    /** Model identifier for the tester. */
    model: string;
    /** Sampling temperature for the tester (lower = more deterministic). */
    temperature: number;
    /** Maximum tokens the tester may generate per turn. */
    maxTokens: number;
  };  
  /**
   * Settings for the OpenAI text-embedding model used to vectorise documents
   * and queries before Pinecone upsert / search.
   */
  embedding: {
    /** Embedding provider — currently only `"openai"` is supported. */
    provider: "openai";
    /** Embedding model identifier (e.g. `"text-embedding-3-small"`). */
    model: string;
    /** Output vector dimensionality — must match the Pinecone index dimension. */
    dimensions: number;
  };
  /**
   * Pinecone index connection settings.
   */
  pinecone: {
    /** Name of the Pinecone index to read from and write to. */
    indexName: string;
    /**
     * Optional namespace within the index.
     * When omitted, vectors are stored in the default namespace.
     */
    namespace?: string;
  };
  /**
   * Document chunking settings applied during ingestion.
   */
  chunking: {
    /**
     * Splitting strategy.
     * `"recursive"` tries progressively smaller separators (paragraphs →
     * lines → sentences → words) to keep chunks semantically coherent.
     */
    strategy: "recursive";
    /** Target chunk size in characters. */
    chunkSize: number;
    /** Number of characters to overlap between consecutive chunks. */
    chunkOverlap: number;
  };
  /**
   * Retrieval settings applied when searching Pinecone at query time.
   */
  retrieval: {
    /** Number of top-scoring chunks to retrieve per query. */
    topK: number;
    /**
     * Minimum cosine similarity score for a chunk to be included.
     * Currently unused — all top-k results are forwarded to the LLM.
     */
    scoreThreshold: number;
  };
  /**
   * Local filesystem storage settings.
   */
  storage: {
    /** Directory where ingested-document metadata JSON files are persisted. */
    dataDir: string;
  };
}
